# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fei.Ren')),
            ],
        ),
        migrations.AddField(
            model_name='chifan',
            name='ren',
            field=models.ManyToManyField(to='fei.Ren'),
        ),
    ]
