# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0003_charge_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ren',
            name='balance',
            field=models.FloatField(editable=False),
        ),
    ]
