# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0004_auto_20160520_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ren',
            name='balance',
            field=models.FloatField(),
        ),
    ]
