# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0006_auto_20160520_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='chifan',
            name='const_share',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
