# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0008_auto_20160520_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 4, 4, 54, 931080, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
