# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0009_charge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chifan_sep',
            name='comment',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
