# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0010_chifan_sep_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chifan',
            name='cost_sharing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chifan',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
