# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0011_auto_20160524_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chifan',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
