# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0013_auto_20160524_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
