# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0014_auto_20160524_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='money',
            field=models.FloatField(verbose_name='hello'),
        ),
    ]
